name: Build and Release ZicNode
on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'

      - name: Build ZicNode (Linux AMD64)
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o zicnode-linux-amd64 main.go

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ZicNode Automatic Build
          tag_name: latest
          files: |
            zicnode-linux-amd64
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
